### ISSUE TITLE
Minor fly bypass (suggest config changes?)

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#47]
**Screenshot (or video recording):** https://gyazo.com/4873c058eb1e3b53e2add2c32082666e

**AntiAura version:** 10.99

**Hacked Client (Set to N/A is none):** Flux B11

**Description:** People can exploit the max height limit for fly by flying just below it. This may act like bhop. People can fly around people 1 block above the ground faster than normal and not get dragged back for speed.

**Comment by ItsMennyo** [comment]
The same as: https://github.com/EthanTG/AntiAura/issues/33

**Comment by ItsMennyo** [comment]
And this can not be changed if you tweak the check in the config. This will be more a problem in AntiAura itself.

**Comment by joehot200** [comment]
This is not the same at #45 as that was before the new configuration option and limit.

However as stated above, this should be able to be solved with simple config changes.

**Comment by joehot200** [comment]
Flight's MaxHeightOffGround will be adjusted to 1.3, from 1.4. The user may adjust this lower if they wish. A height of 1.3 offers no advantage in any scenarios, and therefore will not be patched.

As such this problem is not one I believe that I need to solve, as I do not believe solving this would stop players gaining an advantage, nor do I believe it would make any significant impact in general.
