### ISSUE TITLE
Random Sprint dragback (Imperial Networks)

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#91]
**Screenshot (or video recording):** https://gyazo.com/171488328168492e4547055d0d81ac4c

**AntiAura version:** 11.02

**Minecraft version:** 1.8.8

**Hacked Client (Set to N/A if none):** NOT EVEN HACKING (N/A) :D 

**Description:** I was sprinting on Imperial Networks KitPvP (YES it has AntiAura) and I kept getting dragged back for some unknown reason.

**Comment by joehot200** [comment]
"Some unknown reason" isn't good enough when you have /anotify.

**Comment by EthanTG** [comment]
Care to revise your comment @joehot200? I'm pretty sure you have access to it.

**Comment by Personinblack** [comment]
AntiAura version: 11.02
Minecraft version: 1.8.8 Spigot
Config: https://hastebin.com/esifusipuk.vbs (Threshold is 0.7 because I can't get detected while its more than that and dragbacks are not giving much information)

Same thing is happening on me too... I'm getting dragged back all the time and this is probably because of the sprint check. Anotify only shows "speed" but when I got detected (not just dragged back) it sometimes says "sprint" and I already have the sprint check disabled. Also setting EfficientCheck to true is not solving the issue either.

I can add a video if necessary.

**Comment by EthanTG** [comment]
@Personinblack thanks. Next time please just open a new issue. 

@joehot200 look..
